# Generated by Django 5.1.7 on 2025-03-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.CharField(choices=[('old', 'Старый'), ('new', 'Новый')], default='new', max_length=3)),
            ],
        ),
    ]
