# Generated by Django 5.1.7 on 2025-03-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название курса')),
                ('teacher', models.CharField(max_length=100, verbose_name='Преподаватель')),
                ('prise', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration', models.CharField(max_length=100, verbose_name='Продолжительность')),
                ('course_type', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн')], max_length=100, verbose_name='Формат обучения')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('certificate', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=100, verbose_name='Сертификат')),
            ],
        ),
    ]
